<?php declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/**
 * @var View $block
 */

$enhancedProductAttributeDisplay = $block->getData('enhancedProductAttributeDisplay');
$product = $block->getProduct();
$attributesToRender = $enhancedProductAttributeDisplay->getAttributesToRender($product);
?>
<div class="magebit-attributes-container">
    <ul class="magebit-attribute-list">
        <?php foreach ($attributesToRender as $attributeName => $attributeValue): ?>
            <li class="magebit-attribute-list-item">
                <b class="magebit-attribute-bold-title"><?= $attributeName . ':' ?></b>
                <span class="magebit-attribute-value"><?= $attributeValue ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="magebit-product-short-description">
        <?= $product->getShortDescription(); ?>
    </div>
</div>


